### ISSUE TITLE
Espresso preferences not loading on Ubuntu 20.04.02 LTS

### ISSUE THREAD

**Issue by cubusi** [coadmunkee/gnome-shell-extension-espresso#11]
Hi there!
As you already know, the Preferences are not opening on GNOME 3.36.8.
Code is:
`The settings of extension espresso@coadmunkee.github.com had an error:
```
TypeError: showEspressoBox.prepend is not a function
```

Stack trace:
```
EspressoWidget@/home/ich/.local/share/gnome-shell/extensions/espresso@coadmunkee.github.com/prefs.js:55:25
buildPrefsWidget@/home/ich/.local/share/gnome-shell/extensions/espresso@coadmunkee.github.com/prefs.js:313:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
`
Is there any workaround or option i can use to help this?
This is my first Issue-Report and i want to say thank you for all the coding and efforts for this extension! It is so great to see this commitment in the linux world :)

I'm on:

Ubuntu 20.04.2 LTS
GNOME 3.36.8
X11
Installed Extensions: ArcMenu, OpenWeather, DesktopIcons, User Theme

Thank you!

**Comment by coadmunkee** [comment]
cubusi,

Espresso only supports Gnome 40 variants, and the preferences window in particular won't work with earlier versions of Gnome. Unfortunately, it looks like Ubuntu 21.10 with Gnome 40 is still a few months away.

**Comment by kiamlaluno** [comment]
I thought GNOME Shell would not install an extension that is for GNOME 40, when the Linux distribution is running GNOME 3.38.5. I now learned to check the list of the GNOME Shell versions supported by an extension, before installing it.

**Comment by coadmunkee** [comment]
No problem. This happens fairly often. You can always use the Caffeine
extension with Gnome 3.38 and get the same functionality (Espresso was
actually forked from Caffeine when it looked like they weren't going to
release a Gnome 40 version).

**Comment by cubusi** [comment]
Thank you! I also didn't know that the Extension site would let me install an extension for the wrong shell ;)
Learned something too!
merci
