### ISSUE TITLE
Espresso stays on / not working after LibreOffice Impress Slideshow 

### ISSUE THREAD

**Issue by cubusi** [coadmunkee/gnome-shell-extension-espresso#12]
Hi there,
i just discovered, that when i start a slideshow with LibreOffice on two monitors (one laptop, one extern), the Espresso-Icon is not clickable / working anymore. Espresso keeps disabling the screensaver and auto suspend till logging off and the cup is filled with coffe (or espresso ;) ). I did not discover the problem with other full-screen programs so far.

Its with:

LibreOffice
Version: 6.4.7.2
Build ID: 1:6.4.7-0ubuntu0.20.04.1
CPU threads: 8; OS: Linux 5.8; UI render: default; VCL: gtk3; 

Locale: en-US (en_US.UTF-8); UI-Language: en-US
on:
Ubuntu 20.04.2 LTS
GNOME 3.36.8
X11
Installed Extensions: ArcMenu, OpenWeather, DesktopIcons, User Theme

Thanks for your work!

**Comment by JulioQc** [comment]
Same issue with VMware Player in fullscreen. Not consistent but I'd say 1 out of 5 times I leave the app (shutdown VM and exit vmware player) it'll have espresso stuck enabled and espresso icon is not reactive until logoff or reboot.

**Comment by coadmunkee** [comment]
The newest version of Espresso includes some changes to how Espresso internally handles requests to enable or disable functionality. I believe it may address this particular issue. I have not been able to reproduce this behavior with the current version. If anyone is still experiencing this issue please throw another comment up and I'll start doing more debugging.

**Comment by JulioQc** [comment]
I've updated and re enabled the espresso extension shortly after your comment and been using daily since. 
Unfortunately there's not much improvement. Espresso doesn't toggle itself on full screen app or on app in the list, as it should in the configuration. However, the icon does not freeze anymore and manual enable/disable works better now.

**Comment by coadmunkee** [comment]
JulioQc - can you provide some more information? I am seeking to understand exactly what is happening in your situation so that I can figure out where to troubleshoot. Are you using XOrg or Wayland (or have you tried with both?). Do you use xscreensaver?

Thanks - I'll keep looking into it.

**Comment by JulioQc** [comment]
I'm on Pop!_OS 21.10, Xorg 2:1.20.13-1ubuntu1.1 and GNOME Shell 40.5.  I dont use xscreensaver. 

I set Espresso to stay open on full screen apps and when VMware Player is running. I use VMware Player in full screen all day. When I walk away from the desktop, I notice computer went to sleep upon my return :(

**Comment by JulioQc** [comment]
Hey I tried it all week again and it works perfectly now. You changed something? Anyhow, thanks!

**Comment by coadmunkee** [comment]
Thanks for letting me know. I haven't pinned down what was wrong, nor have I changed anything. Wish I could say I fixed something, but I didn't. I'm going to keep the issue open at least for a little while longer in case it starts happening again.

**Comment by coadmunkee** [comment]
Unable to reproduce with Espresso v7. The method of queueing and processing the addition of removal of inhibitors was changed substantially and I believe it has addressed this issue.
