### ISSUE TITLE
Espresso is a fork of Caffeine

### ISSUE THREAD

**Issue by ckotte** [coadmunkee/gnome-shell-extension-espresso#14]
"Espresso was derived from a fork of the Caffeine extension and provides the same functionality. The extension currently supports Gnome shell "40""

What does this mean? It's not derived from a fork of the caffeine project - it's a fork with a few commits for GNOME 40. Please also create a link to the original project (which is still maintained) so people can easily see where the original code comes from. 

Thanks!

Regards
A contributor of the original project

**Comment by coadmunkee** [comment]
I think we are arguing semantics a bit as I am not sure there is any difference between "a fork with a few commits for Gnome 40" vs "derived from a fork". That being said I am happy to put any additional references or acknowledgements on the Espresso README page. I made some minor README updates based on your original issues submission. Let me know if you think this bring things into a fair balance or not. If not, I am open to suggestions. Honestly, if it my actions with Espresso are a problem for any of the Caffeine maintainers or contributors like yourself, I am willing to retire Espresso altogether.

I am not looking to steal anyone's credit, and I was honestly just trying to quickly get a compatible version of the extension up and running when Gnome 40 was first released. The main message on the Caffeine README says that Caffeine is barely maintained any more and that left me with doubts as to whether or not a Gnome 40 compatible version of Caffeine was going to happen any time soon.

Please do let me know if you still have remaining concerns or issues with either my actions or the Espresso extension in general. I am willing to continue to the discuss until I can make things right.

**Comment by ckotte** [comment]
Why not ask to be the new maintainer of Caffeine instead of creating a new fork? The pull requests also still get approved. This message is in the README for a long time. It also states that new maintainers are welcome...

It's up to you if you want to create a fork or not. You don't need to retire Espresso.

Now it's more clear to me that this is a fork with some "additions". I was surprised to read reviews that Espresso is a more advanced version of Caffeine. I spent a lot of time last year to rewrite the code to make certain features work with Wayland and Night Mode and everything in Espresso looks exactly the same. ;-)
