### ISSUE TITLE
Is there way to enable/disable auto suspend with bash command?

### ISSUE THREAD

**Issue by zheneknew** [coadmunkee/gnome-shell-extension-espresso#19]
Hi!
Is there way to enable/disable auto suspend with bash command?

**Comment by coadmunkee** [comment]
There might be a way to do it, but I am not sure I'd be able to figure that out. The extension uses some defined DBus APIs and javascript classes that are designed to support the APIs.

**Comment by AATLEMIDRM** [comment]
The bash command to activate Caffeine was:

`gsettings --schemadir ~/.local/share/gnome-shell/extensions/caffeine@patapon.info/schemas/ set org.gnome.shell.extensions.caffeine user-enabled true`

and to deactivate:

`gsettings --schemadir ~/.local/share/gnome-shell/extensions/caffeine@patapon.info/schemas/ set org.gnome.shell.extensions.caffeine user-enabled false`

So the corresponding lines for Espresso would be:

`gsettings --schemadir ~/.local/share/gnome-shell/extensions/espresso@coadmunkee.github.com/schemas/ set org.gnome.shell.extensions.espresso user-enabled true`

and

`gsettings --schemadir ~/.local/share/gnome-shell/extensions/espresso@coadmunkee.github.com/schemas/ set org.gnome.shell.extensions.espresso user-enabled false`

But I have no idea if they work or not.

I was just dealing with something on my computer yesterday, and part of that was finding out about Espresso, so I've been using it for less than a day. (Thanks for the fork!)

I am on Ubuntu 22.04 using GNOME 42.5.

When I used that line with Caffeine, it was the full equivalent of clicking the tray icon: The steaming icon was activated, and the notification popped up.

With Espresso, no outward effect appears, but there is also no error message. I have not tested to see if the screen stays on for extended periods, which should be the desired effect.

**Comment by errnoh** [comment]
@AATLEMIDRM based on testing it just now doesn't seem to work as expected. Your suggestion toggles the setting, but as you mentioned the icon doesn't change and most importantly the screen still goes to sleep and after some time the machine suspends as well.
