### ISSUE TITLE
Mention Night Light functionality in the description

### ISSUE THREAD

**Issue by forteller** [coadmunkee/gnome-shell-extension-espresso#21]
I'm really happy that you've added Night Light functionality to Caffeine. Unfortunately you've forgotten to mention that in the e.g.o description, so I didn't find it when looking for an extension like this, until someone mentioned it to me. If you want more people to find this extension you should add a mention of this function, and the "only in full screen" and "only for certain apps" function too.

Thanks! :)

**Comment by coadmunkee** [comment]
Updated the description to mention night light, full screen and select apps functionality. Thanks for the suggestion.

**Comment by lorrin** [comment]
I came here trying to figure out what the Night Light feature is. Still don't know. Can you add an explanation?

**Comment by coadmunkee** [comment]
lorrin - you can read a decent description of the Gnome Night Light feature here: [Gnome's New Night Light Feature ...](https://www.omgubuntu.co.uk/2017/02/gnome-night-light-blue-light-filter-linux)
