### ISSUE TITLE
Typo (applicationa => application)

### ISSUE THREAD

**Issue by jose1711** [coadmunkee/gnome-shell-extension-espresso#26]
https://github.com/coadmunkee/gnome-shell-extension-espresso/blob/91ae20591763f05ec95a0eed16d29d6767a941c7/espresso%40coadmunkee.github.com/schemas/org.gnome.shell.extensions.espresso.gschema.xml#L57

**Comment by coadmunkee** [comment]
thanks for the report. updated to read as "Pause/resume Night Light for defined applications when enabled/disabled"
