### ISSUE TITLE
Configurable self-deactivation period

### ISSUE THREAD

**Issue by alifarazz** [coadmunkee/gnome-shell-extension-espresso#3]
After using the extension for some time; I noticed that after activating it, it automatically self-deactivates after a certian period of time.
Is there any way to change that period or postpone the deactivation indefinitely?

**Comment by coadmunkee** [comment]
Can you provide a few more details? Have you configured Espresso to enable when a full screen application is running or are you simply using the top panel button to activate/deactivate Espresso? Do you have any idea how long it takes to self-deactivate? Do you use any other applications/extensions that also inhibit screensaver and/or suspend?

If you have activated Espresso by toggling the top panel button, there shouldn't be any timeout and it shouldn't self-deactivate.

**Comment by alifarazz** [comment]
> Have you configured Espresso to enable when a full screen application is running or are you simply using the top panel button to activate/deactivate Espresso?

I've set it to enable when a full-screen application is running and I also turn it on when I login in, using the activate/deactivate button on top panel (it's disabled when I login).

> Do you use any other applications/extensions that also inhibit screensaver and/or suspend?

Nope.

> If you have activated Espresso by toggling the top panel button, there shouldn't be any timeout and it shouldn't self-deactivate.

Yeah that's how I enable it, as I mentioned above.

> Do you have any idea how long it takes to self-deactivate?

Somewhere around 30 mins I guess, however I **can not** reproduce this extension's behavior since the day before yesterday and it's been working correctly.
I'll keep a close eye on it and will notify you if this happens again.

**Comment by coadmunkee** [comment]
Thanks for the details. I'll keep the issue open, so let me know if you see the behavior again .

**Comment by speekes1** [comment]
"we're very sorry... the settings for this extension can't be displayed.

**Comment by alifarazz** [comment]
Since our last conversation, I've disabled the add-on's notifiction and it has been working correctly for the past the week 👍.

**Comment by giner** [comment]
Android has this feature nicely done. By clicking the icon you can set one of 5, 10, 30 minutes or ∞:
![caffeine](https://user-images.githubusercontent.com/533434/119216208-59c53f00-bb0d-11eb-9efb-c25661456c20.png)

**Comment by coadmunkee** [comment]
The Caffeine and Espresso extensions both use some straight forward functions to interact with the Gnome session manager through dbus. The session manager functions used to add or remove 'inhibitors' that prevent the suspend functionality generally allow the inhibitor to be turned on or off. The session manager functionality used by the extension doesn't support setting a timeout limit to automatically remove an inhibitor after a set amount of time nor at a specific time. At the moment, I don't have enough 'spare time' to layout an approach to integrating a timer or cron-like functionality into the extension.
