### ISSUE TITLE
The settings for this extension can't be displayed

### ISSUE THREAD

**Issue by markovdigital** [coadmunkee/gnome-shell-extension-espresso#4]
![image](https://user-images.githubusercontent.com/15268617/116005929-8c6d3c00-a622-11eb-96a6-15ba556f9fa8.png)

The settings of extension espresso@coadmunkee.github.com had an error:
```
TypeError: showEspressoBox.prepend is not a function
```

Stacktrace:
```
EspressoWidget@/home/user/.local/share/gnome-shell/extensions/espresso@coadmunkee.github.com/prefs.js:55:25
buildPrefsWidget@/home/user/.local/share/gnome-shell/extensions/espresso@coadmunkee.github.com/prefs.js:313:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

Installed through extensions.gnome.org
Ubuntu 20.10
Gnome 3.38.3
X11

**Comment by coadmunkee** [comment]
markovdigital - Sorry, but I was only able to build support for Gnome 40. The error you are seeing is a result of significant differences between Gtk3 (used with Gnome 3.xx) vs Gtk4 (used with Gnome 40). Honestly, it will probably be easier for you to keep using the original Caffeine until Ubuntu makes the leap to Gnome 40

**Comment by markovdigital** [comment]
@coadmunkee Thank you so much for the quick response!
