### ISSUE TITLE
Please add tags for releases

### ISSUE THREAD

**Issue by smcv** [coadmunkee/gnome-shell-extension-espresso#43]
I'm looking at packaging the Espresso extension for Debian, as a replacement for the Caffeine extension that it was derived from.

Would you mind adding tags or releases to the Github repo for each version that you release to extensions.gnome.org, similar to [what the author of Caffeine did](https://github.com/eonpatapon/gnome-shell-extension-caffeine/tags)? That would make it easier for distributions and contributors to keep track of which commit corresponds to which release on extensions.gnome.org.

I'm a bit confused by the versioning here: the `metadata.json` in this git repository says version 72, but the extensions.gnome.org page says it's only at version 7. Which one is correct? I think it would be easier for everyone if they were the same.

**Comment by smcv** [comment]
For example if version 7 on e.g.o is commit 4ffd413a here, and you are going to use the e.g.o versions as the "official" version number, then you could tag that as a release with commands like:

```
git tag -a -m 'espresso extension v7' v7
git push origin v7
```

**Comment by coadmunkee** [comment]
I added a v7 tag (actually tied to one commit prior to the one you have referenced). e.g.o creates it's own version numbering, but going forward I'll work on aligning the version in metadata.json with the e.g.o version.  Please take a look and let me know if the tag meets your need or not. If not, we can try again.

**Comment by smcv** [comment]
Thanks, that looks great. I'll try to get this packaged soon.

**Comment by coadmunkee** [comment]
Are you planning to package this for the latest bookworm? I didn't maintain any support for versions prior to Gnome 40, and the preferences window will throw an error with Gnome 3.xx versions.

**Comment by smcv** [comment]
> Are you planning to package this for the latest bookworm?

Yes, new packages don't get added to Debian stable releases, only into testing/unstable and experimental. Extensions that get added now will be targeting Debian 12, but will never get into Debian 11, so it doesn't matter whether they're compatible with Debian 11's GNOME Shell 3.38.

Debian 12 is going to ship with GNOME 43 unless something very unexpected happens (GNOME 42 is already in the process of being replaced by 43, and 44 doesn't release until after the freeze for Debian 12 has already started).

**Comment by smcv** [comment]
v7 was tagged, so this can be closed.
