### ISSUE TITLE
German-localized notification text cut off before content

### ISSUE THREAD

**Issue by lorrin** [coadmunkee/gnome-shell-extension-espresso#50]
![image](https://user-images.githubusercontent.com/351893/197363079-c87f901c-fff5-40f3-8c49-938154dd853a.png)

Every notification looks the same ("Sleep mode and screen saver ...") and is cut off before the content that varies. 

Pop!_OS 22.04 LTS / GNOME 42.3.1 / 3840x2160 w/ 200% scaling.

**Comment by coadmunkee** [comment]
Lorrin, Can you provide a better message? There was a similar issue with the Dutch translations and someone contributed an updated locale file which reworded the message to put the enable/disabled part at the beginning. I just don't know enough German to take care of this one myself.

**Comment by lorrin** [comment]
Comparing with the English original, the German isn't that much longer. I think this is probably a bug with Gnome display scaling not allowing enough space for the text, and not an espresso issue.

I wasn't able to think of a way to re-word to put the enable/disable part at the beginning, but I did contribute some missing German translations.

**Comment by coadmunkee** [comment]
@lorrin Will you submit a Pull request for the updated German translations? I think you might only have them locally on your fork.
