### ISSUE TITLE
Meta.MonitorManager.get is evil on gnome44 (mutter deprecated the function)

### ISSUE THREAD

**Issue by xevilstar** [coadmunkee/gnome-shell-extension-espresso#53]
Dear Maintainers,

I am trying to patch this extension to make it work on gnome 44.
To begin with I edited the metadata.js adding the gnome 44 version and installed espresso just to debug it.
Got "Meta.MonitorManager.get is not a function"
Got around searching and ... 
it seems that mutter has retired that function as explained here:
[https://gitlab.gnome.org/GNOME/mutter/-/commit/aa2a663380c6c7b3b0af2269f9713b99d6cace58](https://gitlab.gnome.org/GNOME/mutter/-/commit/aa2a663380c6c7b3b0af2269f9713b99d6cace58)

I have searched inside the espresso latest git tree for a place to apply something similar to this:

[https://gitlab.gnome.org/GNOME/mutter/-/commit/65d8164833e998b35434a70f47808296e131b4a0](https://gitlab.gnome.org/GNOME/mutter/-/commit/65d8164833e998b35434a70f47808296e131b4a0)

still searching ..... 

Can you please help me patch espresso@coadmunkee.github.com/extension.js to make it work with gnome 44 ?

Thanks in advance.

**Comment by vixalien** [comment]
are you on gnome 4.4? or gnome 44?

**Comment by xevilstar** [comment]
gnome 4.4 sorry

**Comment by vixalien** [comment]
I'm sorry but I think I'm confused. the latest gnome shell version is 43.
Are you perhaps talking about gtk 4.4 or are you on a really old version?

**Comment by xevilstar** [comment]
the latest gnome-shell is 4.4 some other extensions are already adapting

[image: Screenshot from 2023-03-08 11-55-32.png]

**Comment by vixalien** [comment]
the latest is Gnome 43 https://release.gnome.org/43/

**Comment by xevilstar** [comment]
> the latest is Gnome 43 https://release.gnome.org/43/

![Screenshot from 2023-03-08 11-55-23](https://user-images.githubusercontent.com/1389525/224027330-4f025f7b-6bf5-4a16-a9a3-0293a5edd48c.png)

**Comment by xevilstar** [comment]
https://download.gnome.org/sources/gnome-shell/44/

**Comment by xevilstar** [comment]
https://download.gnome.org/sources/gnome-shell-extensions/44/

**Comment by vixalien** [comment]
as you can see in the image above, you are on GNOME 44 (not 4.4) which is a beta (pre-release) version....

**Comment by xevilstar** [comment]
please take a look at the shell version of the following extensions ...

https://extensions.gnome.org/extension/3628/arcmenu/
https://extensions.gnome.org/extension/4269/alphabetical-app-grid/
https://extensions.gnome.org/extension/5425/battery-time/
https://extensions.gnome.org/extension/4679/burn-my-windows/
https://extensions.gnome.org/extension/3396/color-picker/
https://extensions.gnome.org/extension/4648/desktop-cube/
https://extensions.gnome.org/extension/3433/fly-pie/
https://extensions.gnome.org/extension/4955/gradient-top-bar/
https://extensions.gnome.org/extension/5263/gtk4-desktop-icons-ng-ding/
https://https://extensions.gnome.org/extension/2896/messaging-menu/extensions.gnome.org/extension/988/harddisk-led/
https://extensions.gnome.org/extension/2236/night-theme-switcher/
https://extensions.gnome.org/extension/5278/pano/
https://extensions.gnome.org/extension/5292/quick-touchpad-toggle/
https://extensions.gnome.org/extension/2899/settingscenter/
https://extensions.gnome.org/extension/5470/weather-oclock/

then read some [basic open source philosophy](https://en.wikipedia.org/wiki/Release_early,_release_often) 


[here](https://www.amazon.com/Cathedral-Bazaar-Musings-Accidental-Revolutionary/dp/0596001088/ref=sr_1_1?crid=2RHHF4DMRIZAF&keywords=the+cathedral+and+the+bizarre&qid=1678695493&sprefix=the+cathedral+and+tha+bazare%2Caps%2C184&sr=8-1) 




about the concept of release early release often

thanks

**Comment by xevilstar** [comment]
nice caffeine just updated to 44 https://extensions.gnome.org/extension/517/caffeine/

**Comment by xevilstar** [comment]
news ?

**Comment by vixalien** [comment]
here's where the `Meta.MonitorManager.get` is used; https://github.com/coadmunkee/gnome-shell-extension-espresso/blob/192b1c9310c69bd4f1be461b160014b22e05f128/espresso%40coadmunkee.github.com/extension.js#L143

**Comment by xevilstar** [comment]
I have tried to change that line but I think I haven't found the right
way to do it

**Comment by vixalien** [comment]
I'll look into this when I get some free time

**Comment by hendersj** [comment]
I've just upgraded openSUSE Tumbleweed to 20230326 today, and that also now includes GNOME 44.0 - and I can confirm this extension no longer works.

**Comment by thimslugga** [comment]
I just rebased to Fedora Silverblue 38 and discovered that this extension still doesn't support gnome shell 44.

**Comment by coadmunkee** [comment]
libanp provided a pull request that addresses the Meta.MonitorManager.get issue. I've merged the pull, so you should be able to build a Gnome 44 compatible version using the master branch. I typically run an arch-based distribution, so haven't installed Gnome 44 yet. I'll spin up a VM and test in the next week or two before packing a new version for the EGO website. If any of you run into problems with the new code, please open additional issues so we can work on resolving them. I'd also be interested in have folks comment here with your distro details if you are having success using the newest version of Espresso on G44.

**Comment by accelbread** [comment]
Using Espresso master branch on G44 successfully. Im on NixOS unstable.

**Comment by coadmunkee** [comment]
Included in Espresso v8 Release
