### ISSUE TITLE
support Fedora 38 and Gnome 44

### ISSUE THREAD

**Issue by donvipre** [coadmunkee/gnome-shell-extension-espresso#57]
Currently extensions.gnome.org tell us that espresso is outdated on the released Fedora 38.

Would you please be so kind to update the features that are required to be supported on Fedora 38?

**Comment by eltel** [comment]
+ 1

**Comment by donvipre** [comment]
I just switched to caffeine. straight forward and working already.
https://extensions.gnome.org/extension/517/caffeine/

**Comment by eltel** [comment]
> I just switched to caffeine. straight forward and working already. https://extensions.gnome.org/extension/517/caffeine/

I couldn't get it to work a few days ago, tried again after seeing this and it works - thanks!

**Comment by coadmunkee** [comment]
Caffeine is always a good option. Espresso was branched from Caffeine when Gnome 40 was released. At that time Caffeine appeared to be pretty dormant and I didn't get any responses from Caffeine maintainers. (Ironic - sorry for the recent lack of responses here). Today's merge of code provided by libanp provide G44 compatibility if you are still interested.
