### ISSUE TITLE
Gnome 46 support

### ISSUE THREAD

**Issue by bhundven** [coadmunkee/gnome-shell-extension-espresso#62]
It would be nice to get Gnome 46 support.

**Comment by coadmunkee** [comment]
I'll be open, I have a ton of real-life stuff keeping from putting time towards Espresso. Unless someone else has time to contribute the required changes it might not happen. You best alternative if you need Gnome 46 in the near term would be switching to Caffeine.

**Comment by bhundven** [comment]
Totally understand!
