### ISSUE TITLE
Needs support for Gnome 46

### ISSUE THREAD

**Issue by theanine** [coadmunkee/gnome-shell-extension-espresso#63]

**Comment by fuxx** [comment]
@coadmunkee do you need any help here?

**Comment by coadmunkee** [comment]
I hear the call for G46 support, but have a bunch of work and life commitments keeping me from being able to work on this any time soon...... @fuxx - I would love help if you are offering

**Comment by InklingGirl** [comment]
Hope all goes well w/ your endeavours @coadmunkee, & I hope another user–developer (I can't code msyelf, just shell script) w/ the free time will step up & contribute a PR to this great piece of F/LOSS.

**Comment by InklingGirl** [comment]
Ubuntu 24.04 LTS w/ GNOME 46 has launched today.

**Comment by InklingGirl** [comment]
🥳
