### ISSUE TITLE
This message popped to me when I installed the extension: 

### ISSUE THREAD

**Issue by MatheusMBD** [coadmunkee/gnome-shell-extension-espresso#8]
![Captura de tela de 2021-05-28 10-39-05](https://user-images.githubusercontent.com/84976355/119992482-fae64680-bfa0-11eb-98bb-46b51d21f07b.png)

And the tecnical details is here:
The settings of extension espresso@coadmunkee.github.com had an error:
```
TypeError: showEspressoBox.prepend is not a function
```

Stack trace:
```
EspressoWidget@/home/matheus/.local/share/gnome-shell/extensions/espresso@coadmunkee.github.com/prefs.js:55:25
buildPrefsWidget@/home/matheus/.local/share/gnome-shell/extensions/espresso@coadmunkee.github.com/prefs.js:313:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by coadmunkee** [comment]
Are you running a version of Gnome prior to Gnome 40? The error message you are getting typically occurs when someone has installed the extension with Gnome 3.38. The Espresso extension only works with Gnome 40, but you can get the same functionality for Gnome 3.38 (and older versions of Gnome) from the Caffeine extension.

**Comment by MatheusMBD** [comment]
>" Are you running a version of Gnome prior to Gnome 40?" 
Yep, I'm using the version 3.36.8. Thank you for your reply, the Caffeine extension works just fine.

**Comment by MatheusMBD** [comment]
I just read the previous closed issues, sorry for I didn't see it before.
