### ISSUE TITLE
icon dissapeard on Fedora 34 Gnome 40.1.0 Wayland

### ISSUE THREAD

**Issue by TuxyKey** [coadmunkee/gnome-shell-extension-espresso#9]
For a while everything worked on Fedora 34 Gnome 40.1.0.
As you know fedora does come with regular updates, and i believe the problem is a kernel update.
It's not only Espresso but also Cpufreq that's having problems.. 
i mentioned the problem in this post..
https://github.com/konkor/cpufreq/issues/180#issuecomment-850855815
Perhaps there is a relation.
So what's going on?
i can install Espresso via Gnome Shell extension and i can see it appear in the install dir under the name  espresso@coadmunkee.github.com
But there is no icon in the top bar for me to activate and or see when it's active.
Unlike cpufreq i can hit the blue configure icon on the gnome shell extension size and the config menu pops up.
no GTK error (like with cpufreq).
in the espresso config menu i can toggle "Show Espresso in top panel" but nothing happens.
When i open pref the show in top panel is active but it's not visible. For a sec i thought perhaps it's dark mode ? but that is'nt the problem.. also there is nothing there clicked like a mad man nothing happend hahaha..
Hope i did not forget anything ?

current kernel is: 5.12.7-300.fc34.x86_64

Thanks for all your effort and great work on this app..

**Comment by coadmunkee** [comment]
Do you use other extensions, and if so are any of them showing up?  I don't use Fedora (my daily driver is EndeavourOS) but my recent upgrade to Gnome 40.1.0 resulted in the switch being flipped to disable all extensions. I had to open the Extensions app and enable extensions again. I know this sounds sort of stupid, but maybe check to make sure Extensions hasn't disable all extensions?

**Comment by TuxyKey** [comment]
Hi @coadmunkee thanks for your help.

(TLDR) it works again you where correct , but how to set it correct changed in fedora and this version of gnome.

i was all ready and typed most of my reply to explain to you that since fedora 34 , the enable/disable extensions is no longer in gnome tweaks tool.. 
But then i really wanted to know how does one disable all extensions in fedora 34 now that it's no longer possible to do it using gnome tweaks tools?

As mentioned the /home/user_id/.local/share/gnome-shell/extensions/
did not show any installed extensions same for the gnome extensions page (installed application tab).

But when typing: gsettings get org.gnome.shell enabled-extensions
i do get output..

gsettings get org.gnome.shell enabled-extensions
['espresso@coadmunkee.github.com', 'no-overview@fthx', 'cpufreq@konkor', 'extension-list@tu.berry', 'apps-menu@gnome-shell-extensions.gcampax.github.com']

searching again i did stumble on the solution and how to toggle the switch you mention..

query the status:
gsettings get org.gnome.shell disable-user-extensions
mine came back true .. and that's not good . and exactly what you said.. ;-) ... very cool !!

setting it to false so i can test it : 
gsettings set org.gnome.shell disable-user-extensions false

and query again shows it's no on false.. 
and now everything is back in working order.

Thanks again will try to see of cpufreq now works..

**Comment by coadmunkee** [comment]
The extension switch that used to be in Gnome Tweaks is not packaged in a separate applet simply named Extensions. I am not familiar with how Fedora organizes packages for dnf, so I am unfortunately not able to provide a simple dnf install command oto tell you how to get the applet. If you open Gnome's Software app and search for 'extension' you should be able to find the applet. It let's you flip those switches without having to mess with gsettings commands.
![image](https://user-images.githubusercontent.com/51798181/120191292-c1534c80-c1e7-11eb-9988-a1228bcfd862.png)

**Comment by TuxyKey** [comment]
thanks i did not know this .. cool.. i searched in gnome software software. and did see it.. but i decided to install it via command line. i used the gnome software to find the project page and see the package name.
i like to keep a txt log of each install that's why i like simple command line.. 
it's just a dnf install gnome-extensions-app.
sudo dnf install gnome-extensions-app 2>&1|tee install_log_gnome_extensions_app_fedora34_31mei2021.txt

for sum reason gnome software shows it's not installed hahah..
but it's installed, perhaps i need to reboot so that gnome software shows it.. hahaa.

![image](https://user-images.githubusercontent.com/32193020/120195129-b1a32a80-c21e-11eb-846e-1b859206ee85.png)

thanks again..
